### ISSUE TITLE
Другая идея по смене различных разговоров

### ISSUE THREAD

**Issue by agent10** [aacidov/DisTypePro-android#9]
@ibakaidov 
Пришла в голову такая идея, поясню на серии скриншотов.
1) В начале у нас вместо одного поля ввода будет сразу два:
![d1](https://cloud.githubusercontent.com/assets/1007354/18119217/a691a5ce-6f6a-11e6-8503-1cfb6c4e1c23.png)
2) Если надо внезапно начать другой разговор - переключаемся на второе поле. При этом автоматически появляется третье, а первое сохраняется как было:
![d2](https://cloud.githubusercontent.com/assets/1007354/18119284/f0c6cfe8-6f6a-11e6-827d-ef06a613c2d9.png)
3) И так далее:
![d3](https://cloud.githubusercontent.com/assets/1007354/18119291/f6ae4936-6f6a-11e6-8d7b-49bfde856c95.png)
4) Если же полностью стереть текст из поля - то оно исчезнет. Но при этом другие разговоры сохранятся как были:
![d4](https://cloud.githubusercontent.com/assets/1007354/18119311/1025edec-6f6b-11e6-8278-a6bbe11f04e6.png)

Таким образом мы сразу видим все разговоры, гораздо быстрее между ними переключаемся, не нужные автоматически удаляются. Ещё можно справа от полей добавить кнопки "-" чтобы быстро удалять разговоры без фокуса на них. 
В дополнении к каждому разговорю можно "привязать" выбранную категорию, чтобы при смене фокуса менялась и категория.
Из минусов этого я вижу то, что одно пустое поле всегда будет занимать вертикальное место экрана. Но тут есть варианты как и этого избежать.

Сейчас же пока интересует подходит ли сама концепция сохранения разговоров в таком виде?

**Comment by ibakaidov** [comment]
@agent10 я подумаю, пока не очень нравится, не понимаю как с лишними движениями это будет. хм, я подумаю

**Comment by naivekook** [comment]
Всем привет!
А почему бы не сделать Viewpager c табами?
По умолчанию будет две вкладки "чат 1" и "чат 2" и кнопка для добавления нового чата. Таким образом переключаться между чатами можно будет либо по кнопке таба либо свайпом.

![page 1](https://cloud.githubusercontent.com/assets/1501831/18440870/59a8c794-7913-11e6-9ea9-7b8929d41b63.png)

**Comment by naivekook** [comment]
@agent10 можешь посмотреть как получилось
https://github.com/aacidov/DisTypePro-android/pull/12
